
## anime

### list
GET http://localhost:7001/api/v1/anime HTTP/1.1
content-type: application/json

## pokemon

### list
GET http://127.0.0.1:7001/api/v1/pokemon

## video

### 列表页
GET http://127.0.0.1:7001/api/v1/video

### 详情页
GET http://127.0.0.1:7001/api/v1/video/372058

### 图片
GET http://127.0.0.1:7001/api/v1/video/image/q719jXXEzOoYaps6babgKnONONX

## music

### 列表页
GET http://127.0.0.1:7001/api/v1/music?singer=one%20ok%20rock

### 详情页
GET http://127.0.0.1:7001/api/v1/music/0p1YL9nzIuKTonZH6Gq58i

### 图片
GET http://127.0.0.1:7001/api/v1/music/image/ab67616d0000b2730f94f53a1c9c60d953ffd2f2