
## anime

### list
GET http://localhost:7001/api/v1/anime HTTP/1.1
content-type: application/json

## pokemon

### list
GET http://127.0.0.1:7001/api/v1/pokemon

## video

### 列表页
GET http://127.0.0.1:7001/api/v1/video

### 详情页
GET http://127.0.0.1:7001/api/v1/video/372058

### 图片
GET http://127.0.0.1:7001/api/v1/video/image/q719jXXEzOoYaps6babgKnONONX

